function F = FcomputeOptim(nodesCoord,xi,eta,ec)

% Computation of the displacement gradient tensor (used to compute the 
% Green-Lagrange strain tensor)
% Inputs:   - nodesCoord, the Lagrangian (in undeformed state) coordinates 
%             of the element's nodes (4x2)
%           - xi + eta, the parent coordinates of isoparametric formulation
%           - ec, the Eulerian (current deformed state) coordinates
%             of the element's nodes (x = X + u_x) (8x1) 

% c = reshape(nodesCoord',[],1);

c = nodesCoord'; c = c(:);

F = zeros(2,2);
F(1,1) = (c(2)*ec(3) - c(6)*ec(3) - c(2)*ec(7) + c(6)*ec(7) - c(6)*ec(1)*eta -...
    c(2)*ec(3)*eta + c(2)*ec(5)*eta + c(6)*ec(7)*eta + c(6)*ec(1)*xi - c(6)*ec(3)*xi -...
    c(2)*ec(5)*xi + c(2)*ec(7)*xi + c(8)*(ec(1) - ec(5)*(1 + eta) - ec(1)*xi +...
    ec(3)*(eta + xi)) + c(4)*(ec(1)*(-1 + eta) + ec(5)*(1 + xi) - ec(7)*(eta + xi)))/...
    (c(4)*c(5) - c(3)*c(6) + c(6)*c(7) - c(5)*c(8) - c(4)*c(7)*eta + c(6)*c(7)*eta +...
    c(3)*c(8)*eta - c(5)*c(8)*eta + c(2)*(c(3) - c(3)*eta + c(5)*(eta - xi) + c(7)*...
    (-1 + xi)) + c(4)*c(5)*xi - c(3)*c(6)*xi - c(4)*c(7)*xi + c(3)*c(8)*xi + c(1)*(c(8) +...
    c(4)*(-1 + eta) - c(8)*xi + c(6)*(-eta + xi)));

F(1,2) = (-(c(1)*ec(3)) + c(5)*ec(3) + c(1)*ec(7) - c(5)*ec(7) + c(5)*ec(1)*eta +...
    c(1)*ec(3)*eta - c(1)*ec(5)*eta - c(5)*ec(7)*eta - c(5)*ec(1)*xi + c(5)*ec(3)*xi +...
    c(1)*ec(5)*xi - c(1)*ec(7)*xi + c(7)*(ec(5)*(1 + eta) + ec(1)*(-1 + xi) - ec(3)*...
    (eta + xi)) + c(3)*(ec(1) - ec(1)*eta - ec(5)*(1 + xi) + ec(7)*(eta + xi)))/(c(4)*...
    c(5) - c(3)*c(6) + c(6)*c(7) - c(5)*c(8) - c(4)*c(7)*eta + c(6)*c(7)*eta + c(3)*...
    c(8)*eta - c(5)*c(8)*eta + c(2)*(c(3) - c(3)*eta + c(5)*(eta - xi) + c(7)*(-1 +...
    xi)) + c(4)*c(5)*xi - c(3)*c(6)*xi - c(4)*c(7)*xi + c(3)*c(8)*xi + c(1)*(c(8) +...
    c(4)*(-1 + eta) - c(8)*xi + c(6)*(-eta + xi)));

F(2,1) = (c(2)*ec(4) - c(6)*ec(4) - c(2)*ec(8) + c(6)*ec(8) - c(6)*ec(2)*eta - c(2)*...
    ec(4)*eta + c(2)*ec(6)*eta + c(6)*ec(8)*eta + c(6)*ec(2)*xi - c(6)*ec(4)*xi -...
    c(2)*ec(6)*xi + c(2)*ec(8)*xi + c(8)*(ec(2) - ec(6)*(1 + eta) - ec(2)*xi + ec(4)*...
    (eta + xi)) + c(4)*(ec(2)*(-1 + eta) + ec(6)*(1 + xi) - ec(8)*(eta + xi)))/(c(4)*...
    c(5) - c(3)*c(6) + c(6)*c(7) - c(5)*c(8) - c(4)*c(7)*eta + c(6)*c(7)*eta + c(3)*...
    c(8)*eta - c(5)*c(8)*eta + c(2)*(c(3) - c(3)*eta + c(5)*(eta - xi) + c(7)*...
    (-1 + xi)) + c(4)*c(5)*xi - c(3)*c(6)*xi - c(4)*c(7)*xi + c(3)*c(8)*xi + c(1)*...
    (c(8) + c(4)*(-1 + eta) - c(8)*xi + c(6)*(-eta + xi)));

F(2,2) = (-(c(1)*ec(4)) + c(5)*ec(4) + c(1)*ec(8) - c(5)*ec(8) + c(5)*ec(2)*eta + ...
    c(1)*ec(4)*eta - c(1)*ec(6)*eta - c(5)*ec(8)*eta - c(5)*ec(2)*xi + c(5)*ec(4)*xi +...
    c(1)*ec(6)*xi - c(1)*ec(8)*xi + c(7)*(ec(6)*(1 + eta) + ec(2)*(-1 + xi) - ec(4)*...
    (eta + xi)) + c(3)*(ec(2) - ec(2)*eta - ec(6)*(1 + xi) + ec(8)*(eta + xi)))/(c(4)*...
    c(5) - c(3)*c(6) + c(6)*c(7) - c(5)*c(8) - c(4)*c(7)*eta + c(6)*c(7)*eta + c(3)*...
    c(8)*eta - c(5)*c(8)*eta + c(2)*(c(3) - c(3)*eta + c(5)*(eta - xi) + c(7)*(-1 +...
    xi)) + c(4)*c(5)*xi - c(3)*c(6)*xi - c(4)*c(7)*xi + c(3)*c(8)*xi + c(1)*(c(8) +...
    c(4)*(-1 + eta) - c(8)*xi + c(6)*(-eta + xi)));

end

